export const SET_INGREDIENTS_FROM_DB = 'SET_INGREDIENTS_FROM_DB';
export const SET_PRICE_FROM_DB = 'SET_PRICE_FROM_DB';
export const DB_FETCH_FAILED = 'DB_FETCH_FAILED'

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const LOADING = 'LOADING';

export const STORE_ORDER = 'STORE_ORDER';
export const ORDER_ERROR = 'ORDER_ERROR';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";
