export const SET_INGREDIENTS_FROM_DB = 'SET_INGREDIENTS_FROM_DB';
export const SET_PRICE_FROM_DB = 'SET_PRICE_FROM_DB';
export const GET_INGREDIENT_PRICES_BY_SAGA = "GET_INGREDIENT_PRICES_BY_SAGA";
export const GET_INGREDIENTS_BY_SAGA = "GET_INGREDIENTS_BY_SAGA";
export const DB_FETCH_FAILED = 'DB_FETCH_FAILED'

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const LOADING = 'LOADING';

export const STORE_ORDER = 'STORE_ORDER';
export const ORDER_ERROR = 'ORDER_ERROR';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASING_BURGER_BY_SAGA = "PURCHASING_BURGER_BY_SAGA";
export const GET_ORDERS_BY_SAGA = "GET_ORDERS_BY_SAGA";

export const AUTH_USER_WITH_SAGA = "AUTH_USER_WITH_SAGA";
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_INITIATE_TIMEOUT_CHECK = "AUTH_INITIATE_TIMEOUT_CHECK"
export const AUTH_CHECK_STATE_BY_SAGA = "AUTH_CHECK_STATE_BY_SAGA";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";
