export const GET_INGREDIENTS_FROM_DB = 'GET_INGREDIENTS_FROM_DB';
export const GET_PRICE_FROM_DB = 'GET_PRICE_FROM_DB';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';